name: Ramakrishna
description: ramakrishna School managemental application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  # HTTP requests
  http: ^1.1.0
  
  # State management (optional, if needed)
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true